# Generated by Django 4.2 on 2026-02-26 09:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=100, verbose_name='Brend')),
                ('model', models.CharField(db_index=True, max_length=100, verbose_name='Model')),
                ('imei', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='IMEI')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Narx')),
                ('stock_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ombordagi soni')),
                ('warranty_months', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kafolat muddati (oylar)')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Ta'rif")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='products_pr_brand_4bfaa4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['model'], name='products_pr_model_268e30_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['imei'], name='products_pr_imei_fc98f0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_quantity'], name='products_pr_stock_q_ba97b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('brand', 'model', 'imei')},
        ),
    ]
