# Generated by Django 4.2 on 2026-02-26 09:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="To'lov miqdori")),
                ('payment_date', models.DateField(auto_now_add=True, db_index=True, verbose_name="To'lov sanasi")),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Karta'), ('transfer', "O'tkazma")], default='cash', max_length=20, verbose_name="To'lov usuli")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Sana')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Qadri')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bitta mahsulot narxi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Umumiy narx')),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Karta'), ('credit', 'Nasiya')], default='cash', max_length=10, verbose_name="To'lov turi")),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="To'langan summa")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('is_completed', models.BooleanField(default=True, verbose_name="To'liq to'langan")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='Mijoz')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Savdo',
                'verbose_name_plural': 'Savdolar',
                'ordering': ['-date'],
            },
        ),
    ]
