# Generated by Django 4.2 on 2026-02-26 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familyasi')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Otasining ismi')),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998XXXXXXXXX formatida bo'lishi kerak", regex='^\\+?998\\d{9}$')], verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('passport_number', models.CharField(max_length=50, unique=True, verbose_name='Pasport raqami')),
                ('passport_issued_date', models.DateField(verbose_name='Pasport berilgan sana')),
                ('passport_issued_by', models.CharField(max_length=200, verbose_name='Pasport bergan organ')),
                ('registered_date', models.DateField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['-registered_date'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='customers_c_phone_n_cabfe1_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['passport_number'], name='customers_c_passpor_442bd6_idx'),
        ),
    ]
